import { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import {
  fetchAttendance,
  markAttendance,
  updateAttendance
} from "../features/attendance/attendanceSlice";
import { applyLeave, fetchLeaves } from "../features/leave/leaveSlice";
import { fetchUsers } from "../features/users/userSlice";
import LogoutButton from "../components/LogoutButton";
import {
  calculateSalaryDeductions,
  calculateCheckoutPayroll,
  formatTime,
  getAttendanceTotal,
  getLocalDateKey,
  getMonthKey,
  getPayrollRates,
  monthlyWorkHours,
  normalHours,
  roundMoney
} from "../utils/payroll";

const pdfPageWidth = 595.28;
const pdfPageHeight = 841.89;
const pdfMargin = 36;

const escapePdfText = (value) =>
  String(value ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");

const cleanPdfFileName = (value) =>
  String(value || "salary-slip")
    .trim()
    .replace(/[^a-z0-9]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();

const downloadBlob = (blob, fileName) => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
};

const createSalarySlipPdf = ({
  user,
  monthName,
  monthlySalary,
  dailySalary,
  monthlyPaidDays,
  paidLeaveDays,
  unpaidLeaveDays,
  salarySummary,
  rows
}) => {
  const pages = [];
  let commands = [];
  let currentY = pdfPageHeight - pdfMargin;

  const addText = (text, x, y, size = 10, bold = false) => {
    commands.push(
      `0.07 0.09 0.15 rg BT /${
        bold ? "F2" : "F1"
      } ${size} Tf ${x} ${y} Td (${escapePdfText(text)}) Tj ET`
    );
  };

  const addLine = (x1, y1, x2, y2) => {
    commands.push(`${x1} ${y1} m ${x2} ${y2} l S`);
  };

  const addRect = (x, y, width, height, fill = false) => {
    commands.push(`${x} ${y} ${width} ${height} re ${fill ? "f" : "S"}`);
  };

  const addFill = (r, g, b) => {
    commands.push(`${r} ${g} ${b} rg`);
  };

  const addStroke = (r, g, b) => {
    commands.push(`${r} ${g} ${b} RG`);
  };

  const addFooter = () => {
    addStroke(0.82, 0.85, 0.9);
    addLine(pdfMargin, 42, pdfPageWidth - pdfMargin, 42);
    addText("Generated by HRMS", pdfMargin, 24, 9);
  };

  const finishPage = () => {
    addFooter();
    pages.push(commands.join("\n"));
  };

  const startPage = (continued = false) => {
    commands = [];
    currentY = pdfPageHeight - pdfMargin;
    addStroke(0.07, 0.09, 0.15);
    addText("Salary Slip", pdfMargin, currentY, 22, true);
    addText(monthName, pdfPageWidth - 150, currentY + 2, 12, true);
    currentY -= 20;
    addLine(pdfMargin, currentY, pdfPageWidth - pdfMargin, currentY);
    currentY -= 24;
    if (continued) {
      addText(`${user.name} - continued`, pdfMargin, currentY, 13, true);
      currentY -= 22;
    }
  };

  const ensureSpace = (height) => {
    if (currentY - height < 58) {
      finishPage();
      startPage(true);
    }
  };

  const drawSummaryBox = (label, value, x, y, width) => {
    addStroke(0.82, 0.85, 0.9);
    addRect(x, y - 34, width, 44);
    addText(label, x + 8, y - 8, 8);
    addText(value, x + 8, y - 24, 11, true);
  };

  const drawTableHeader = () => {
    const widths = [72, 78, 78, 54, 112, 78];
    const headers = ["Date", "Check In", "Check Out", "Hours", "Day Type", "Salary"];
    let x = pdfMargin;

    addFill(0.94, 0.95, 0.97);
    addRect(pdfMargin, currentY - 18, pdfPageWidth - pdfMargin * 2, 22, true);
    addStroke(0.82, 0.85, 0.9);

    headers.forEach((header, index) => {
      addText(header, x + 5, currentY - 10, 8, true);
      x += widths[index];
    });
    currentY -= 22;
  };

  startPage();
  addText(user.name, pdfMargin, currentY, 14, true);
  addText(user.email || "", pdfMargin, currentY - 16, 10);
  addText(`Join Date: ${user.joinDate || "-"}`, pdfPageWidth - 170, currentY, 10);
  currentY -= 44;

  const boxWidth = 124;
  const gap = 10;
  const summaryItems = [
    ["Monthly Salary", `Rs ${monthlySalary}`],
    ["Daily Salary", `Rs ${roundMoney(dailySalary)}`],
    ["Paid Days", monthlyPaidDays],
    ["Paid Leave", paidLeaveDays],
    ["Unpaid Leave", unpaidLeaveDays],
    ["Gross Pay", `Rs ${salarySummary.grossSalary}`],
    ["Leave Deduction", `Rs ${salarySummary.otherDeduction}`],
    ["Tax Deduction", `Rs ${salarySummary.taxDeduction}`],
    ["PF 12%", `Rs ${salarySummary.pfDeduction}`],
    ["Net Salary", `Rs ${salarySummary.netSalary}`]
  ];

  summaryItems.forEach(([label, value], index) => {
    const col = index % 4;
    const row = Math.floor(index / 4);
    drawSummaryBox(
      label,
      value,
      pdfMargin + col * (boxWidth + gap),
      currentY - row * 54,
      boxWidth
    );
  });
  currentY -= Math.ceil(summaryItems.length / 4) * 54 + 8;

  addText("Attendance Details", pdfMargin, currentY, 13, true);
  currentY -= 18;
  drawTableHeader();

  const columnX = [pdfMargin, 108, 186, 264, 318, 430];
  const tableRows = rows.length
    ? rows
    : [["No attendance found", "-", "-", "-", "-", "-"]];

  tableRows.forEach((row) => {
    ensureSpace(24);
    if (currentY > pdfPageHeight - pdfMargin - 60) {
      drawTableHeader();
    }
    addStroke(0.9, 0.92, 0.95);
    addLine(pdfMargin, currentY - 14, pdfPageWidth - pdfMargin, currentY - 14);
    row.forEach((cell, index) => {
      addText(cell, columnX[index] + 5, currentY - 8, 8);
    });
    currentY -= 20;
  });

  currentY -= 10;
  ensureSpace(40);
  addText(
    `Net Salary: Rs ${salarySummary.netSalary}`,
    pdfPageWidth - 190,
    currentY,
    16,
    true
  );

  finishPage();

  const objects = [];
  const pageObjectNumbers = [];
  const contentObjectNumbers = [];

  pages.forEach((page) => {
    pageObjectNumbers.push(objects.length + 1);
    objects.push("");
    contentObjectNumbers.push(objects.length + 1);
    objects.push(`<< /Length ${page.length} >>\nstream\n${page}\nendstream`);
  });

  const fontRegularObjectNumber = objects.length + 1;
  objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const fontBoldObjectNumber = objects.length + 1;
  objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");
  const pagesObjectNumber = objects.length + 1;
  const catalogObjectNumber = objects.length + 2;

  pageObjectNumbers.forEach((pageObjectNumber, index) => {
    objects[pageObjectNumber - 1] =
      `<< /Type /Page /Parent ${pagesObjectNumber} 0 R /MediaBox [0 0 ${pdfPageWidth} ${pdfPageHeight}] ` +
      `/Resources << /Font << /F1 ${fontRegularObjectNumber} 0 R /F2 ${fontBoldObjectNumber} 0 R >> >> ` +
      `/Contents ${contentObjectNumbers[index]} 0 R >>`;
  });

  objects.push(
    `<< /Type /Pages /Kids ${pageObjectNumbers
      .map((number) => `${number} 0 R`)
      .join(" ")} /Count ${pageObjectNumbers.length} >>`
  );
  objects.push(`<< /Type /Catalog /Pages ${pagesObjectNumber} 0 R >>`);

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogObjectNumber} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return new Blob([pdf], { type: "application/pdf" });
};

export default function Employee() {
  const dispatch = useDispatch();

  const [date, setDate] = useState("");
  const [reason, setReason] = useState("");
  const [activeTab, setActiveTab] = useState("attendance");
  const [now, setNow] = useState(new Date());
  const [selectedMonth, setSelectedMonth] = useState(getMonthKey());

  const savedUser = JSON.parse(localStorage.getItem("user") || "null");
  const attendance = useSelector((state) => state.attendance.list);
  const leaves = useSelector((state) => state.leave.list);
  const users = useSelector((state) => state.users.list);

  const user = useMemo(() => {
    return (
      users.find((item) => item.id === savedUser?.id) ||
      users.find((item) => item.email === savedUser?.email) ||
      savedUser
    );
  }, [savedUser, users]);

  useEffect(() => {
    dispatch(fetchAttendance());
    dispatch(fetchLeaves());
    dispatch(fetchUsers());
  }, [dispatch]);

  useEffect(() => {
    const timer = setInterval(() => setNow(new Date()), 1000);
    return () => clearInterval(timer);
  }, []);

  const today = getLocalDateKey();

  const myLeaves = useMemo(() => {
    return leaves.filter(
      (leave) =>
        leave.userId === user?.id ||
        leave.email === user?.email ||
        leave.name === user?.name
    );
  }, [leaves, user?.email, user?.id, user?.name]);

  const myAttendance = useMemo(() => {
    return attendance.filter(
      (item) =>
        item.userId === user?.id ||
        item.email === user?.email ||
        item.name === user?.name
    );
  }, [attendance, user?.email, user?.id, user?.name]);

  const todayAttendance = myAttendance.find(
    (item) =>
      item.date === today &&
      item.dayType !== "paid-sunday" &&
      item.status !== "paid-sunday"
  );
  const todayLeave = myLeaves.find(
    (leave) => leave.date === today && leave.status !== "rejected"
  );
  const activeAttendance = myAttendance.find(
    (item) => item.date === today && item.status === "checked-in"
  );

  const monthlySalary = Number(user?.monthlySalary || user?.salary || 0);
  const joinMonthKey = user?.joinDate ? getMonthKey(user.joinDate) : "";
  const { dailySalary, hourlySalary } = getPayrollRates(monthlySalary);
  const totalLeaves = myLeaves.length;
  const pendingLeaves = myLeaves.filter((l) => l.status === "pending").length;
  const approvedLeaves = myLeaves.filter((l) => l.status === "approved").length;
  const visibleAttendance = myAttendance.filter(
    (item) => item.dayType !== "paid-sunday" && item.status !== "paid-sunday"
  );
  const salaryMonthKey = selectedMonth || getMonthKey();
  const isBeforeJoinMonth =
    joinMonthKey && salaryMonthKey.localeCompare(joinMonthKey) < 0;
  const monthlyAttendance = visibleAttendance.filter((item) =>
    !isBeforeJoinMonth && String(item.date || "").startsWith(salaryMonthKey)
  );
  const monthlyPaidDays = monthlyAttendance.filter(
    (item) => item.status === "completed"
  ).length;
  const monthlyApprovedLeaves = myLeaves.filter(
    (leave) =>
      !isBeforeJoinMonth &&
      leave.status === "approved" &&
      String(leave.date || "").startsWith(salaryMonthKey)
  );
  const paidLeaveDays = Math.min(1, monthlyApprovedLeaves.length);
  const unpaidLeaveDays = Math.max(0, monthlyApprovedLeaves.length - paidLeaveDays);
  const paidLeaveAmount = roundMoney(dailySalary * paidLeaveDays);
  const leaveDeduction = roundMoney(dailySalary * unpaidLeaveDays);
  const attendanceSalary = getAttendanceTotal(monthlyAttendance);
  const monthlyGrossSalary = roundMoney(attendanceSalary + paidLeaveAmount);
  const salarySummary = calculateSalaryDeductions(
    monthlyGrossSalary,
    leaveDeduction
  );

  if (!user) {
    return <h3>Please login again</h3>;
  }

  const handleApply = () => {
    if (!date || !reason.trim()) {
      alert("Leave date and reason required");
      return;
    }

    dispatch(
      applyLeave({
        userId: user.id,
        name: user.name,
        email: user.email,
        field: user.field || "",
        managerId: user.managerId || "",
        managerName: user.managerName || "",
        date,
        reason,
        status: "pending"
      })
    );
    setDate("");
    setReason("");
  };

  const handleAttendance = () => {
    if (!monthlySalary) {
      alert("Monthly salary admin panel me set karo");
      return;
    }

    const currentTime = new Date();

    if (!activeAttendance) {
      if (todayLeave) {
        alert("Aaj leave applied hai, check in nahi kar sakte");
        return;
      }

      if (todayAttendance) {
        alert("Today attendance already completed");
        return;
      }

      dispatch(
        markAttendance({
          userId: user.id,
          name: user.name,
          email: user.email,
          date: today,
          checkIn: currentTime.toLocaleTimeString(),
          checkInAt: currentTime.toISOString(),
          checkOut: "",
          checkOutAt: "",
          normalHours,
          monthlySalary,
          hourlySalary,
          workedHours: 0,
          overtimeHours: 0,
          salaryAmount: 0,
          status: "checked-in"
        })
      );
      return;
    }

    const payroll = calculateCheckoutPayroll({
      checkInAt: activeAttendance.checkInAt,
      checkOutAt: currentTime.toISOString(),
      monthlySalary
    });

    dispatch(
      updateAttendance({
        ...activeAttendance,
        checkOut: currentTime.toLocaleTimeString(),
        checkOutAt: currentTime.toISOString(),
        workedHours: payroll.workedHours,
        overtimeHours: payroll.overtimeHours,
        salaryAmount: payroll.salaryAmount,
        dayType: payroll.dayType,
        status: "completed"
      })
    );
  };

  const handleDownloadSalarySlip = () => {
    const salaryMonth = new Date(`${salaryMonthKey}-01T00:00:00`);
    const monthName = salaryMonth.toLocaleString("default", {
      month: "long",
      year: "numeric"
    });
    const attendanceRows = monthlyAttendance.map((item) => [
      item.date,
      item.dayType === "paid-sunday" ? "Sunday Paid" : formatTime(item.checkInAt),
      item.dayType === "paid-sunday" ? "Sunday Paid" : formatTime(item.checkOutAt),
      item.workedHours || 0,
      item.dayType || item.status || "-",
      `Rs ${item.salaryAmount || 0}`
    ]);
    const leaveRows = monthlyApprovedLeaves.map((leave, index) => {
      const isPaidLeave = index === 0;
      const leaveAmount = roundMoney(dailySalary);
      return [
        leave.date,
        "-",
        "-",
        "0",
        isPaidLeave ? "Paid Leave" : "Unpaid Leave",
        isPaidLeave ? `Rs ${leaveAmount}` : `- Rs ${leaveAmount}`
      ];
    });
    const fileName = `${cleanPdfFileName(user.name)}-${salaryMonthKey}-salary-slip.pdf`;
    const pdfBlob = createSalarySlipPdf({
      user,
      monthName,
      monthlySalary,
      dailySalary,
      monthlyPaidDays,
      paidLeaveDays,
      unpaidLeaveDays,
      salarySummary,
      rows: [...attendanceRows, ...leaveRows]
    });

    downloadBlob(pdfBlob, fileName);
  };

  return (
    <main className="page-shell">
      <section className="panel">
        <div className="section-heading">
          <div>
            <h2>Employee Dashboard</h2>
            <p>{user.name} salary and attendance</p>
          </div>
          <div className="heading-actions">
            <span className="clock">{now.toLocaleTimeString()}</span>
            <LogoutButton />
          </div>
        </div>

        <div className="stat-grid">
          <div className="stat-card">
            <span>Monthly Salary</span>
            <strong>Rs {monthlySalary || 0}</strong>
          </div>
          <div className="stat-card">
            <span>Hourly Rate</span>
            <strong>Rs {roundMoney(hourlySalary)}</strong>
          </div>
          <div className="stat-card">
            <span>Daily Salary</span>
            <strong>Rs {roundMoney(dailySalary)}</strong>
          </div>
          <div className="stat-card">
            <span>Month Hours</span>
            <strong>{monthlyWorkHours} hr</strong>
          </div>
          <div className="stat-card">
            <span>Today Status</span>
            <strong>
              {activeAttendance
                ? "Checked In"
                : todayLeave
                ? "On Leave"
                : todayAttendance?.checkOutAt
                ? "Completed"
                : "Not Started"}
            </strong>
          </div>
          <div className="stat-card">
            <span>Today Salary</span>
            <strong>Rs {todayAttendance?.salaryAmount || 0}</strong>
          </div>
        </div>

        <div className="tabs">
          <button
            className={activeTab === "attendance" ? "active-tab" : ""}
            onClick={() => setActiveTab("attendance")}
          >
            Attendance
          </button>
          <button
            className={activeTab === "leave" ? "active-tab" : ""}
            onClick={() => setActiveTab("leave")}
          >
            Leave
          </button>
          <button className="print-btn" onClick={handleDownloadSalarySlip}>
            Download Salary Slip
          </button>
          <input
            className="month-picker"
            type="month"
            value={selectedMonth}
            min={joinMonthKey || undefined}
            onChange={(e) => setSelectedMonth(e.target.value)}
          />
        </div>

        {activeTab === "attendance" && (
          <div className="attendance-box">
            {todayLeave && !activeAttendance ? (
              <div className="leave-day-note">
                <strong>On Leave</strong>
                <span>Check in is closed for today's leave request.</span>
              </div>
            ) : (
              <button className="attendance-btn" onClick={handleAttendance}>
                {activeAttendance ? "Check Out" : "Check In"}
              </button>
            )}

            <div className="attendance-details">
              <div>
                <span>Check In</span>
                <strong>{formatTime(todayAttendance?.checkInAt)}</strong>
              </div>
              <div>
                <span>Check Out</span>
                <strong>{formatTime(todayAttendance?.checkOutAt)}</strong>
              </div>
              <div>
                <span>Worked Hours</span>
                <strong>{todayAttendance?.workedHours || 0} hr</strong>
              </div>
              <div>
                <span>Overtime</span>
                <strong>{todayAttendance?.overtimeHours || 0} hr</strong>
              </div>
              <div>
                <span>Day Type</span>
                <strong>{todayAttendance?.dayType || todayAttendance?.status || "-"}</strong>
              </div>
            </div>
          </div>
        )}

        {activeTab === "leave" && (
          <div className="leave-box">
            <div className="employee-form two-column">
              <input
                type="date"
                value={date}
                onChange={(e) => setDate(e.target.value)}
              />
              <input
                placeholder="Reason"
                value={reason}
                onChange={(e) => setReason(e.target.value)}
              />
            </div>
            <button className="primary-btn" onClick={handleApply}>
              Apply Leave
            </button>
          </div>
        )}
      </section>

      <section className="panel">
        <div className="stat-grid">
          <div className="stat-card">
            <span>Total Leaves</span>
            <strong>{totalLeaves}</strong>
          </div>
          <div className="stat-card">
            <span>Pending</span>
            <strong>{pendingLeaves}</strong>
          </div>
          <div className="stat-card">
            <span>Approved</span>
            <strong>{approvedLeaves}</strong>
          </div>
          <div className="stat-card">
            <span>Paid Leave</span>
            <strong>{paidLeaveDays}</strong>
          </div>
          <div className="stat-card">
            <span>Unpaid Leave</span>
            <strong>{unpaidLeaveDays}</strong>
          </div>
          <div className="stat-card">
            <span>Gross Pay</span>
            <strong>Rs {salarySummary.grossSalary}</strong>
          </div>
          <div className="stat-card">
            <span>Leave Cut</span>
            <strong>Rs {salarySummary.otherDeduction}</strong>
          </div>
          <div className="stat-card">
            <span>Tax Cut</span>
            <strong>Rs {salarySummary.taxDeduction}</strong>
          </div>
          <div className="stat-card">
            <span>PF Cut</span>
            <strong>Rs {salarySummary.pfDeduction}</strong>
          </div>
          <div className="stat-card">
            <span>Net Pay</span>
            <strong>Rs {salarySummary.netSalary}</strong>
          </div>
        </div>

        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Check In</th>
                <th>Check Out</th>
                <th>Hours</th>
                <th>Overtime</th>
                <th>Type</th>
                <th>Salary</th>
              </tr>
            </thead>
            <tbody>
              {monthlyAttendance.map((item) => (
                <tr key={item.id}>
                  <td data-label="Date">{item.date}</td>
                  <td data-label="Check In">{item.dayType === "paid-sunday" ? "Sunday Paid" : formatTime(item.checkInAt)}</td>
                  <td data-label="Check Out">{item.dayType === "paid-sunday" ? "Sunday Paid" : formatTime(item.checkOutAt)}</td>
                  <td data-label="Hours">{item.workedHours || 0}</td>
                  <td data-label="Overtime">{item.overtimeHours || 0}</td>
                  <td data-label="Type">{item.dayType || item.status || "-"}</td>
                  <td data-label="Salary">Rs {item.salaryAmount || 0}</td>
                </tr>
              ))}
              {monthlyAttendance.length === 0 && (
                <tr>
                  <td className="table-empty-cell" colSpan="7">No attendance found for selected month</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </section>
    </main>
  );
}
